# Site settings
title: Beauty Under Capitalism
email: hi@beautyundercapitalism.com
tagline: Vote with your wallet.
description: Cosmetics, skincare + haircare database of brands founded/owned by Women of Color.
baseurl: ""
url: ""
encoding: utf-8
lang: en
future: true

# Build settings
permalink: pretty
sass:
  sass_dir: _scss
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed

# collections
collections:
  list-black:
    permalink: black-women-owned-beauty-brands
    output: true
  list-latinx:
    permalink: latina-owned-beauty-brands
    output: true
  list-mena:
    permalink: mena-owned-beauty-brands
    output: true
  list-asian:
    permalink: asian-owned-beauty-brands
    output: true
  list-problematic:
    permalink: problematic
    output: true

exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
